# 003. Numpy and Linear Algebra (선형대수)

- 수치 data 를 다루는데 효율적이고 높은 성능 제공

- 각종 수학적 함수 제공

- Python scientific library 들이 Numpy 기반으로 구축

## ndarray

- n-dimensional array (다차원 배열 객체) 로 구성 

In [1]:
import sys
import numpy as np

In [2]:
# 스칼라
x = 6
x

6

In [3]:
# 벡터
x = np.array([1,2,3])
x

array([1, 2, 3])

In [4]:
print("vector dimension {}".format(x.shape))
print("vector size {}".format(x.size))

vector dimension (3,)
vector size 3


## np.arange()
- range() 와 동일한 기능의 numpy version

In [4]:
arr = np.arange(0, 30, 2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

## np.linspace()

np.linspace(start, end, num)  - [start, end] 를 균일한 간격으로 num 개 element 생성

In [2]:
arr = np.linspace(0, 20, 30)
arr

array([ 0.        ,  0.68965517,  1.37931034,  2.06896552,  2.75862069,
        3.44827586,  4.13793103,  4.82758621,  5.51724138,  6.20689655,
        6.89655172,  7.5862069 ,  8.27586207,  8.96551724,  9.65517241,
       10.34482759, 11.03448276, 11.72413793, 12.4137931 , 13.10344828,
       13.79310345, 14.48275862, 15.17241379, 15.86206897, 16.55172414,
       17.24137931, 17.93103448, 18.62068966, 19.31034483, 20.        ])

## matrix

In [3]:
y = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
print("array dimension {}".format(y.shape))
print("array size {}".format(y.size))

array dimension (3, 3)
array size 9


In [7]:
# 주어진 dimension 의 matrix 정의
x = np.ones((2,3))
print(x)

[[1. 1. 1.]
 [1. 1. 1.]]


In [8]:
print("array dimension {}".format(x.shape))
print("array size {}".format(x.size))

array dimension (2, 3)
array size 6


In [9]:
x = np.ones((3,3,3))
print(x)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [10]:
print("array dimension {}".format(x.shape))
print("array size {}".format(x.size))
print("array length {}".format(len(x)))

array dimension (3, 3, 3)
array size 27
array length 3


## Indexing / Slicing

<img src="axes.png" width="600">

<img src="numpy.png" width="400">



<img src="tensor.jpg" width="600">

In [11]:
# indexing matrix
A = np.ones((5,5), dtype=np.int)
print(A)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [12]:
A[0]

array([1, 1, 1, 1, 1])

In [13]:
A[0,1] = 2
print(A)

[[1 2 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [14]:
A[:, 0] = 3
print(A)

[[3 2 1 1 1]
 [3 1 1 1 1]
 [3 1 1 1 1]
 [3 1 1 1 1]
 [3 1 1 1 1]]


In [15]:
A[:,:] = 5
print(A)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [16]:
A = np.zeros((3,3,3), dtype=np.int)
A[:, :, 0] = 3
print(A)

[[[3 0 0]
  [3 0 0]
  [3 0 0]]

 [[3 0 0]
  [3 0 0]
  [3 0 0]]

 [[3 0 0]
  [3 0 0]
  [3 0 0]]]


In [17]:
A = np.zeros((3,3,3), dtype=np.int)
A[0, :, :] = 3
A[2,2,2] = 9
print(A)

[[[3 3 3]
  [3 3 3]
  [3 3 3]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 9]]]


In [18]:
A = np.zeros((3,3,3), dtype=np.int)
A[:, 0, :] = 3
print(A)

[[[3 3 3]
  [0 0 0]
  [0 0 0]]

 [[3 3 3]
  [0 0 0]
  [0 0 0]]

 [[3 3 3]
  [0 0 0]
  [0 0 0]]]


In [19]:
A = np.zeros((3,3,3), dtype=np.int)
A[:, 0, 0] = 3
print(A)

[[[3 0 0]
  [0 0 0]
  [0 0 0]]

 [[3 0 0]
  [0 0 0]
  [0 0 0]]

 [[3 0 0]
  [0 0 0]
  [0 0 0]]]


In [20]:
A[-1, -1, -1] = -1
A

array([[[ 3,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 3,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 3,  0,  0],
        [ 0,  0,  0],
        [ 0,  0, -1]]])

In [21]:
A[-2, -2, -2] = -2
A

array([[[ 3,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 3,  0,  0],
        [ 0, -2,  0],
        [ 0,  0,  0]],

       [[ 3,  0,  0],
        [ 0,  0,  0],
        [ 0,  0, -1]]])

## Slicing

<img src="numpy1.png" width="300">

In [22]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
arr[:2, 1:]

array([[2, 3],
       [5, 6]])

In [24]:
arr[2]

array([7, 8, 9])

In [25]:
arr[2, :]

array([7, 8, 9])

In [26]:
arr[2:, :]

array([[7, 8, 9]])

In [27]:
arr[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [28]:
arr[1, :2]

array([4, 5])

In [29]:
arr[1:2, :2]

array([[4, 5]])

### matrix 간의 연산 (Element-wise)

### broadcasting

- 서로 dimension 이 다른 두개의 array 를 연산할 때 더 큰 쪽의 axes 에 작은 쪽 array 를 반복시켜 match 시키는 것

<img src="broadcasting.png" width="350">

In [35]:
a = np.array([1, 2, 3, 4])
b = 1
print(a + b)

[2 3 4 5]


In [36]:
a = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]])
b = np.array([0, 1, 2])
print(a + b)

[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


In [37]:
a = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]])
b = np.array([[0], [1], [2], [3]])

print(np.add(a, b))

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]]


In [38]:
print(a * b)

[[ 0  0  0]
 [ 3  4  5]
 [12 14 16]
 [27 30 33]]


In [39]:
np.multiply(a, b)

array([[ 0,  0,  0],
       [ 3,  4,  5],
       [12, 14, 16],
       [27, 30, 33]])

In [40]:
print(a - b)
print()
print(np.subtract(a, b))

[[0 1 2]
 [2 3 4]
 [4 5 6]
 [6 7 8]]

[[0 1 2]
 [2 3 4]
 [4 5 6]
 [6 7 8]]


In [41]:
c = np.array([[1, 2], [1, 2]])
print(c)

[[1 2]
 [1 2]]


In [42]:
print(a - c)

ValueError: operands could not be broadcast together with shapes (4,3) (2,2) 

## random value

np.random.random_sample  -  [0.0, 1.0)  사이의 random 숫자   
> alias : np.random.random   ((n, m))  
> np.random.rand (n, m) : parameter 받는 형식만 차이. 결과 동일(Matlab 사용자들을 위한 편의 제공)


np.random.randn - 표준정규분포의 random 숫자

In [62]:
np.random.seed(10)

In [63]:
print(np.random.random_sample((3, 2)))
print()
print(np.random.random((3, 2)))         # alias of random_sample

[[0.77132064 0.02075195]
 [0.63364823 0.74880388]
 [0.49850701 0.22479665]]

[[0.19806286 0.76053071]
 [0.16911084 0.08833981]
 [0.68535982 0.95339335]]


In [64]:
np.random.rand(3, 2)                             # same as random.random_sample

array([[0.00394827, 0.51219226],
       [0.81262096, 0.61252607],
       [0.72175532, 0.29187607]])

In [65]:
np.random.randn(3, 2)

array([[ 0.22863013,  0.44513761],
       [-1.13660221,  0.13513688],
       [ 1.484537  , -1.07980489]])

## Boolean Indexing

In [67]:
x = np.array([-2, 0, 4, 6, -8, 5, 9, 2])
x

array([-2,  0,  4,  6, -8,  5,  9,  2])

In [68]:
x < 0

array([ True, False, False, False,  True, False, False, False])

In [69]:
x[x < 0]

array([-2, -8])

## Fancy Indexing

- 정수나 불린(Boolean) 값을 가지는 다른 Numpy 배열로 배열을 인덱싱할 수 있는 기능


<img src="fancyindex.png" width="500">

In [79]:
arr = np.arange(0, 15).reshape(5, 3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [80]:
arr[[1, 2]]

array([[3, 4, 5],
       [6, 7, 8]])

In [81]:
arr[[-1, -2]]

array([[12, 13, 14],
       [ 9, 10, 11]])

In [87]:
arr = np.arange(40).reshape(8, 5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]]


In [89]:
# 26, 33, 37 : [[5, 6 , 7], [1, 3, 2]]
arr[[5, 6 , 7], [1, 3, 2]]

array([26, 33, 37])

## mean, std, var, sum, cumsum, min, max, argmin, argmax

In [92]:
arr = np.arange(20).reshape(4, 5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [93]:
arr.sum()

190

In [94]:
arr.mean()

9.5

In [95]:
arr.std()

5.766281297335398

In [96]:
arr.mean(axis=0)

array([ 7.5,  8.5,  9.5, 10.5, 11.5])

In [97]:
arr.mean(axis=1)

array([ 2.,  7., 12., 17.])

In [98]:
print(arr)
print()
print(arr.cumsum(axis=0))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

[[ 0  1  2  3  4]
 [ 5  7  9 11 13]
 [15 18 21 24 27]
 [30 34 38 42 46]]


In [102]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [103]:
arr.max()

19

In [104]:
print(arr.argmax())
print(arr.argmax(axis=1))
print(arr.argmax(axis=0))

19
[4 4 4 4]
[3 3 3 3 3]


In [105]:
print(arr.argmin())
print(arr.argmin(axis=1))
print(arr.argmin(axis=0))

0
[0 0 0 0]
[0 0 0 0 0]
